### ISSUE TITLE
Manual installation failed

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/ds#8]
Hi, here are my steps 

- download zip file from https://github.com/backdrop-contrib/ds 
- on url /admin/modules/install selected manual install, selected "Upload a module, theme, or layout archive to install", uploaded fiel ds-1.x-2.x.zip

I am getting the following error message:

Error message The info file (temporary://update-extraction-fec697d9/ds-1.x-2.x/modules/ds_search/ds_search.info) does not define a 'type' attribute.

**Comment by olafgrabienski** [comment]
If I recall correct, that happened to me with some other module. The fix was to add the 'type' attribute to the `.info` file in question.

As a workaround in the meantime, the installation should work after uploading the extracted module to your code base via FTP, or after downloading and extracting it to your code base using the command line.

**Comment by irinaz** [comment]
@olafgrabienski , thanks, I will update info file and submit pull request. thanks a lot!

**Comment by hosef** [comment]
I added the type property to all of the info files.
